"""classrooms and membership

Revision ID: 109f3ea4dc77
Revises: dab3305db3b1
Create Date: 2026-09-05 19:26:23.266291
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '109f3ea4dc77'
down_revision: str | None = 'dab3305db3b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.Enum('personal', 'public', name='classroom_type'), server_default='personal', nullable=False),
    sa.Column('theme_color', sa.String(length=60), server_default=sa.text("'from-blue-500 to-indigo-600'"), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_classrooms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classrooms'))
    )
    op.create_index(op.f('ix_classrooms_code'), 'classrooms', ['code'], unique=True)
    op.create_index(op.f('ix_classrooms_owner_id'), 'classrooms', ['owner_id'], unique=False)
    op.create_table('classroom_members',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'teacher', 'student', name='member_role'), server_default='student', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_classroom_members_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_classroom_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_members')),
    sa.UniqueConstraint('classroom_id', 'user_id', name='uq_classroom_members_classroom_user')
    )
    op.create_index(op.f('ix_classroom_members_classroom_id'), 'classroom_members', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_members_user_id'), 'classroom_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classroom_members_user_id'), table_name='classroom_members')
    op.drop_index(op.f('ix_classroom_members_classroom_id'), table_name='classroom_members')
    op.drop_table('classroom_members')
    op.drop_index(op.f('ix_classrooms_owner_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_code'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
