"""supporting features

Revision ID: 25b2859d9b0e
Revises: f661c04e6903
Create Date: 2026-09-13 20:19:42.688165
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '25b2859d9b0e'
down_revision: str | None = 'f661c04e6903'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('web', 'android', 'ios', name='push_platform'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_push_tokens_token'))
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String(length=300)), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='quiz_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_quiz_questions_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quiz_questions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_index('ix_quiz_questions_classroom_id_started_at', 'quiz_questions', ['classroom_id', 'started_at'], unique=False)
    op.create_index('uq_quiz_questions_one_active', 'quiz_questions', ['classroom_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('quiz_answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('penalty_seconds', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_answers_question_id_quiz_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_quiz_answers_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_answers')),
    sa.UniqueConstraint('question_id', 'student_id', name='uq_quiz_answers_question_student')
    )
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_student_id'), 'quiz_answers', ['student_id'], unique=False)
    op.add_column('classroom_posts', sa.Column('due_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_posts', 'due_reminder_sent_at')
    op.drop_index(op.f('ix_quiz_answers_student_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index('uq_quiz_questions_one_active', table_name='quiz_questions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_quiz_questions_classroom_id_started_at', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    # ### end Alembic commands ###
    # Dropping a table leaves its enum types behind, and the next upgrade then
    # fails with "type already exists".
    for name in ('quiz_status', 'push_platform'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
