"""attendance sessions records and verifications

Revision ID: b0bd3f8457c4
Revises: cc2a893145a9
Create Date: 2026-09-13 18:47:26.003966
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b0bd3f8457c4'
down_revision: str | None = 'cc2a893145a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('started_by', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('monitoring', 'active', 'ended', name='attendance_session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('rssi_threshold', sa.Integer(), nullable=False),
    sa.Column('hop_depth', sa.Integer(), nullable=False),
    sa.Column('beacon_secret', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_attendance_sessions_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_attendance_sessions_started_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sessions'))
    )
    op.create_index(op.f('ix_attendance_sessions_classroom_id'), 'attendance_sessions', ['classroom_id'], unique=False)
    op.create_index('ix_attendance_sessions_classroom_id_started_at', 'attendance_sessions', ['classroom_id', 'started_at'], unique=False)
    op.create_index('uq_attendance_sessions_one_open_per_classroom', 'attendance_sessions', ['classroom_id'], unique=True, postgresql_where=sa.text("status <> 'ended'"))
    op.create_table('attendance_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'present', 'absent', name='attendance_record_status'), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], name=op.f('fk_attendance_records_corrected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name=op.f('fk_attendance_records_session_id_attendance_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_attendance_records_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_records_session_student')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('attendance_verifications',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('avg_rssi', sa.Integer(), nullable=True),
    sa.Column('hop_count', sa.Integer(), nullable=True),
    sa.Column('valid_windows', sa.Integer(), nullable=False),
    sa.Column('elapsed_windows', sa.Integer(), nullable=False),
    sa.Column('device_id_hash', sa.String(length=128), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], name=op.f('fk_attendance_verifications_session_id_attendance_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_attendance_verifications_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_verifications'))
    )
    op.create_index('ix_attendance_verifications_session_id_student_id', 'attendance_verifications', ['session_id', 'student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_verifications_session_id_student_id', table_name='attendance_verifications')
    op.drop_table('attendance_verifications')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('uq_attendance_sessions_one_open_per_classroom', table_name='attendance_sessions', postgresql_where=sa.text("status <> 'ended'"))
    op.drop_index('ix_attendance_sessions_classroom_id_started_at', table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_classroom_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
    # Autogenerate never drops enum types, so a downgrade followed by an upgrade
    # would fail with "type ... already exists".
    sa.Enum(name='attendance_record_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='attendance_session_status').drop(op.get_bind(), checkfirst=True)
