"""classroom posts and submissions

Revision ID: cc2a893145a9
Revises: c4c4797e0e3f
Create Date: 2026-09-13 15:06:19.380755
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cc2a893145a9'
down_revision: str | None = 'c4c4797e0e3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_posts',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('material', 'announcement', 'assignment', name='post_kind'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_classroom_posts_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_classroom_posts_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_classroom_posts_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_posts'))
    )
    op.create_index(op.f('ix_classroom_posts_author_id'), 'classroom_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_classroom_posts_classroom_id'), 'classroom_posts', ['classroom_id'], unique=False)
    op.create_index('ix_classroom_posts_classroom_id_kind_created_at', 'classroom_posts', ['classroom_id', 'kind', 'created_at'], unique=False)
    op.create_table('submissions',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_submissions_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['classroom_posts.id'], name=op.f('fk_submissions_post_id_classroom_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_submissions_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('post_id', 'student_id', name='uq_submissions_post_student')
    )
    op.create_index(op.f('ix_submissions_post_id'), 'submissions', ['post_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_post_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_classroom_posts_classroom_id_kind_created_at', table_name='classroom_posts')
    op.drop_index(op.f('ix_classroom_posts_classroom_id'), table_name='classroom_posts')
    op.drop_index(op.f('ix_classroom_posts_author_id'), table_name='classroom_posts')
    op.drop_table('classroom_posts')
    # ### end Alembic commands ###
    # Autogenerate never drops enum types, so a downgrade followed by an upgrade
    # would fail with "type post_kind already exists".
    sa.Enum(name='post_kind').drop(op.get_bind(), checkfirst=True)
