"""anti proxy security

Revision ID: f661c04e6903
Revises: b0bd3f8457c4
Create Date: 2026-09-13 19:54:01.133668
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'f661c04e6903'
down_revision: str | None = 'b0bd3f8457c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_enrollments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embeddings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_face_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_enrollments')),
    sa.UniqueConstraint('user_id', name=op.f('uq_face_enrollments_user_id'))
    )
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', name='otp_purpose'), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index('ix_otp_codes_user_id_purpose_created_at', 'otp_codes', ['user_id', 'purpose', 'created_at'], unique=False)
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='device_platform'), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_user_devices_revoked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices'))
    )
    op.create_index('ix_user_devices_fingerprint_hash', 'user_devices', ['fingerprint_hash'], unique=False)
    op.create_index('uq_user_devices_active_public_key', 'user_devices', ['public_key'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_user_devices_one_active_per_user', 'user_devices', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('security_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('multi_device', 'shared_device', 'wrong_device', 'invalid_signature', name='security_alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('medium', 'critical', name='security_alert_severity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_security_alerts_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_alerts'))
    )
    op.create_index('ix_security_alerts_classroom_id_created_at', 'security_alerts', ['classroom_id', 'created_at'], unique=False)
    op.create_table('student_blocks',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], name=op.f('fk_student_blocks_blocked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_student_blocks_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cleared_by'], ['users.id'], name=op.f('fk_student_blocks_cleared_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_blocks_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_blocks'))
    )
    op.create_index(op.f('ix_student_blocks_classroom_id'), 'student_blocks', ['classroom_id'], unique=False)
    op.create_index('uq_student_blocks_one_active', 'student_blocks', ['classroom_id', 'student_id'], unique=True, postgresql_where=sa.text('cleared_at IS NULL'))
    op.add_column('attendance_verifications', sa.Column('device_id', sa.UUID(), nullable=True))
    op.add_column('attendance_verifications', sa.Column('nonce', sa.String(length=64), nullable=True))
    op.create_index('uq_attendance_verifications_accepted_nonce', 'attendance_verifications', ['device_id', 'nonce'], unique=True, postgresql_where=sa.text('accepted AND nonce IS NOT NULL'))
    op.create_foreign_key(op.f('fk_attendance_verifications_device_id_user_devices'), 'attendance_verifications', 'user_devices', ['device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_attendance_verifications_device_id_user_devices'), 'attendance_verifications', type_='foreignkey')
    op.drop_index('uq_attendance_verifications_accepted_nonce', table_name='attendance_verifications', postgresql_where=sa.text('accepted AND nonce IS NOT NULL'))
    op.drop_column('attendance_verifications', 'nonce')
    op.drop_column('attendance_verifications', 'device_id')
    op.drop_index('uq_student_blocks_one_active', table_name='student_blocks', postgresql_where=sa.text('cleared_at IS NULL'))
    op.drop_index(op.f('ix_student_blocks_classroom_id'), table_name='student_blocks')
    op.drop_table('student_blocks')
    op.drop_index('ix_security_alerts_classroom_id_created_at', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index('uq_user_devices_one_active_per_user', table_name='user_devices', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('uq_user_devices_active_public_key', table_name='user_devices', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_user_devices_fingerprint_hash', table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index('ix_otp_codes_user_id_purpose_created_at', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('face_enrollments')
    # ### end Alembic commands ###
    # Autogenerate never drops enum types; without this a downgrade followed by
    # an upgrade fails with "type ... already exists".
    for name in ('security_alert_severity', 'security_alert_type', 'device_platform', 'otp_purpose'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
